version: '3.9'

services:
  web:
    build:
      context: .

    image: ${IMAGE_NAME}

    container_name: ${CONTAINER_NAME}

    restart: always

    stdin_open: true

    tty: true

    volumes:
      #      - ./app:/home/app
      - $PWD/app:/home/app
    #      - $PWD\app:/home/app"

    ports:
      - ${PORT}:${PORT}
